version: "3.8"



services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    restart: always

  redis:
    image: redis:alpine
    restart: always
  
  bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      - redis